# -*- coding: utf-8 -*-
"""ThesisV2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1K3-vr1qLhmx3wwegi51g3MzGGxFePeHF

# Stage 0: Mounting the Drive
"""

from google.colab import drive
drive.mount('/content/drive')

"""Stage 1: Loading data"""

import pandas as pd

df = pd.read_excel('/content/drive/MyDrive/ThesisFiles/DataCollection.xlsx')

print("First 5 rows of the DataFrame:")
print(df.head())

print("\nColumn names and their data types:")
print(df.info())

print("\nConcise summary of the DataFrame:")
print(df.describe(include='all'))

"""Stage2: preprocessing"""

import numpy as np

phase_questions = {
    'Before': [
        'Does the organization have an information security incident management policy?\n*Evidence required: Incident management policy document.',
        'Does   the organization regularly update the existing information security policies?      \n*Evidence required:\u00a0\u00a0Record of changes to the last policies.      \n  ',
        'Does   the organization have an information security incident management plan?       \n*Evidence required:\u00a0Incident Response Plan.      \n  ',
        'Did the organization establish an Incident Management Team (IMT)?\n*Evidence required:\u00a0IMT structures, hierarchy, roles, and tasks of IMT staff members. ',
        'Did the organization establish an Incident Response Team (IRT)?\n*Evidence required:\u00a0IRT structures, hierarchy, roles, and tasks of IRT staff members.',
        'Did   the organization have an appropriate training plan program for IRT personnel?      \n*Evidence required:\u00a0Training plan and program for IRT personnel. ',
        'Does the organization engage interested parties in incident response management?  \n*Evidence required:\u00a0Document containing communication procedures actions such as: Incident notification procedure...',
        'Does   the organization have an incident management information system according to   IMP?      \n*Evidence required:\u00a0Deployed an incident   management information system.       \n',
        'Does the organization implement controls to prevent and mitigate security   incidents to meet the requirements of the plan?      \n*Evidence required:\u00a0Controls such as: (network security devices, p...',
        'Does   the organization have an awareness and training plan and program on   information security incident and vulnerability management?      \n*Evidence required:\u00a0Information security awareness an...',
        'Does   the organization have a plan to test incident management processes and   procedures?      \n*Evidence required:\u00a0Test plan\n Periodic tests\n Conducting exercises to check   processes/procedure...',
        'Does   the organization execute the existing test plan regularly?      \n*Evidence required:\u00a0Tests results.\n',
        'Does   the organization have an incident response capability monitoring program?\u00a0\n*Evidence required:\u00a0Incident response capability monitoring program.      \n'
    ],
    'During': [
        'Is the organization  monitoring and logging system and network activity?\n*Evidence required:\u00a0Log file\n User Activity Monitoring\n Log Analysis and Alerting\n Network Monitoring.\n',
        'Does   the organization detect and report the occurrence of information security   events or the existence of information security vulnerabilities?      \n*Evidence required:\u00a0Monitoring tools deplo...',
        'Did   the organization have a process in place to collect detailed information and   all news related to this event, and properly log the collected incident data   for later analysis?      \n*Evide...',
        'Did   the organization analyse the external/internal threats to gain an   understanding of the threat environment and the changes that have occurred?      \n*Evidence required:\u00a0Records of incident ...',
        'Did   you communicate information related to the incident occurrence to relevant   stakeholders?      \n*Evidence required:\u00a0Records\u00a0of communication with concerned parties related to the incident o...',
        'Are   IR personnel aware of their responsibilities and have all the necessary   documents needed to perform their duties?       \n*Evidence required:\u00a0Record of documents distribution lists of   res...',
        'Does   the organization evaluate information security events to determine if they   constitute incidents, triage them, and prioritize all information   security\u00a0incidents?      \n*Evidence required...',
        'Does   the organization activate the required response teams?      \n*Evidence required:Records of communication during real   incidents, such as: Emails - Slack/Teams messages - Ticketing system  ...',
        'Does   the organization start the timer for the response?       \n*Evidence required:\u00a0Logs showing automated timer start events/logged   trigger times.      \n',
        'Does   the organization use a documented change management process to ensure proper   control and security of incident related artifacts or documents?      \n*Evidence required:\u00a0Record of approved ...',
        'Does   the organization evaluate the proposed resolution with targeted/affected   teams to confirm it meets their needs?      \n*Evidence required:Formal confirmation that the proposed   resolution...',
        'Does   the IRT properly investigate every reported incident?\u00a0\n*Evidence required:\u00a0Incident   investigation report.      \n',
        'Does   the organization check if the incident is under control; if not, escalate it   to the crisis management team?      \n*Evidence required:\u00a0Completed incident status checklists (containment   v...',
        'Does the organization assign internal resources and identify external resources in   order to respond to an incident?      \n*Evidence required:\u00a0Internal\nExternal Resource Allocation and   identifi...',
        'Does   the organization follow defined communication protocols to notify authorized   internal and external stakeholders about the incident and share necessary   details to support response and re...'
    ],
    'After': [
        'Does   the organization close the incident in accordance with the information   security incident management policy and notify all interested parties?       \n*Evidence required:\u00a0Formal Closure Rec...',
        'Does   the organization review how effective the processes, procedures, reporting,   and organizational structure were in handling and recovering from the incident?      \n*Evidence required:\u00a0Post-...',
        'Does   the organization identify, document, and communicate the lessons learned from   information security incidents?      *Evidence required:\u00a0Lessons Learned Documentation and follow-up tracked ...',
        'Does   the organization review, identify, and improve the implementation and update   of security controls, and update the incident management policy if needed (E2)?      \n*Evidence required:\u00a0Reco...',
        'Does   the organization review, identify, and make improvements to the   organization\'s existing information security risk assessment?      \n*Evidence required:\u00a0Updated risk assessments and regist...',
        'Does   the organization communicate and share the results of review with   trusted/select stakeholders?\u00a0\n*Evidence required:\u00a0Record of shared Communication regarding incidents   after their resolu...',
        'Does   the organization share the results with partners?      \n*Evidence required:\u00a0Record of shared Communication regarding incidents after their resolution with stakeholders and partners.',
        'Does   the organization perform a comprehensive evaluation of IRT performance and   effectiveness periodically?      \n*Evidence required:\u00a0Periodic post-incident team performance reviews: Performan...'
    ]
}

question_to_phase = {}
for phase, questions in phase_questions.items():
    for q in questions:
        question_to_phase[q] = phase

score_mapping = {
    'Yes, and we have the evidence': 10,
    'Yes, but not sure about the evidence': 7,
    'In progress': 5,
    'No but planned': 3,
    'No': 0,
    np.nan: 0
}

MAX_QUESTION_SCORE = 10

df.columns = df.columns.str.strip()

sector_column_name = 'What sector does your organization operate in?'
if sector_column_name not in df.columns:
    print(f"Warning: '{sector_column_name}' not found in DataFrame columns after stripping. Using original name if available.")

question_columns = [col for col in df.columns if col not in ['ID', 'Start time', 'Completion time', 'Email', 'Name', 'Last modified time', 'Do you wish to participate in this study?!', sector_column_name]]

df_long = df.melt(id_vars=['ID', sector_column_name],
                   value_vars=question_columns,
                   var_name='Question Text',
                   value_name='Answer')

df_long['Phase'] = df_long['Question Text'].map(question_to_phase)

df_long['Score'] = df_long['Answer'].map(score_mapping)

df_long['Max Score'] = MAX_QUESTION_SCORE

df_long = df_long.rename(columns={'ID': 'Organization ID'})

org_id_mapping = {4: 'Organization A', 5: 'Organization B', 6: 'Organization C', 7: 'Organization D'}
df_long['Organization ID'] = df_long['Organization ID'].map(org_id_mapping)

df_long.dropna(subset=['Phase'], inplace=True)

print("Preprocessed DataFrame head:")
print(df_long.head())
print("\nPreprocessed DataFrame info:")
print(df_long.info())

phase_scores_actual_df = df_long.groupby(['Organization ID', 'Phase']).agg(
    total_score=('Score', 'sum'),
    total_max_score=('Max Score', 'sum')
).reset_index()

phase_scores_actual_df['Compliance Score (%)'] = (phase_scores_actual_df['total_score'] / phase_scores_actual_df['total_max_score']) * 100

print("Phase-wise Compliance Scores (Actual Data):")
print(phase_scores_actual_df[['Organization ID', 'Phase', 'Compliance Score (%)']])

overall_scores_actual_df = phase_scores_actual_df.groupby('Organization ID')['Compliance Score (%)'].mean().reset_index()

print("Overall Compliance Scores (Actual Data):")
print(overall_scores_actual_df)

import matplotlib.pyplot as plt
import pandas as pd

pivot_df = phase_scores_actual_df.pivot(index='Organization ID', columns='Phase', values='Compliance Score (%)').reset_index()

if not pivot_df.empty:
    expected_phases = ['Before', 'During', 'After']
    existing_phases = [p for p in expected_phases if p in pivot_df.columns]

    if len(existing_phases) == len(expected_phases):
        pivot_df = pivot_df[['Organization ID'] + expected_phases]
    else:
        print(f"Warning: Not all expected phase columns {expected_phases} are present in pivot_df. Existing columns: {pivot_df.columns.tolist()}")
else:
    print("Warning: The pivoted DataFrame (pivot_df) is empty. Cannot generate chart.")

print("Pivoted DataFrame for Chart Visualization:")
print(pivot_df.head())

import matplotlib.pyplot as plt
import numpy as np

phases = ['Before', 'During', 'After']
org_ids = pivot_df['Organization ID'].tolist()

fig, axes = plt.subplots(1, 3, figsize=(18, 6), sharey=True)
fig.suptitle('Phase-wise Compliance Scores Across Organizations', fontsize=16)

for i, phase in enumerate(phases):
    ax = axes[i]
    scores = pivot_df[phase].tolist()

    ax.bar(org_ids, scores, color='skyblue')

    ax.set_title(f'Compliance Score for {phase} Phase')
    ax.set_xlabel('Organization Name')
    ax.set_ylabel('Compliance Score (%)')
    ax.set_ylim(0, 100)
    ax.tick_params(axis='x', rotation=45)

    for bar in ax.patches:
        ax.text(bar.get_x() + bar.get_width() / 2,
                bar.get_height() + 2,
                f'{bar.get_height():.1f}%',
                ha='center', va='bottom')

plt.tight_layout(rect=[0, 0.03, 1, 0.95])
plt.show()

recommendations = {}
for index, row in pivot_df.iterrows():
    org_id = row['Organization ID']
    scores = row[['Before', 'During', 'After']]

    weakest_phase = scores.idxmin()
    lowest_score = scores.min()

    if weakest_phase == 'Before':
        recommendation = (
            f"Organization {org_id} has a weakness in the 'Before' phase (Score: {lowest_score:.2f}%). "
            "Recommendation: Focus on strengthening incident preparedness, including policy development, "
            "planning, team establishment, training programs, and regular testing of incident management processes. "
            "Ensure all documentation and controls are in place and regularly updated."
        )
    elif weakest_phase == 'During':
        recommendation = (
            f"Organization {org_id} has a weakness in the 'During' phase (Score: {lowest_score:.2f}%). "
            "Recommendation: Improve incident detection, analysis, and response capabilities. "
            "This includes enhancing monitoring and logging, improving event detection and reporting, "
            "streamlining incident investigation and containment procedures, and ensuring timely communication "
            "with stakeholders during an active incident."
        )
    elif weakest_phase == 'After':
        recommendation = (
            f"Organization {org_id} has a weakness in the 'After' phase (Score: {lowest_score:.2f}%). "
            "Recommendation: Enhance post-incident activities such as formal incident closure, "
            "thorough post-incident reviews to assess effectiveness, comprehensive identification and communication "
            "of lessons learned, and implementing improvements to security controls and risk assessments based on these lessons. "
            "Ensure results are shared with relevant stakeholders and partners."
        )
    else:
        recommendation = f"Organization {org_id}: No specific weakness identified based on phase scores, or all scores are high."

    recommendations[org_id] = recommendation

print("\nIdentified Weaknesses and Recommendations:")
for org_id, rec in recommendations.items():
    print(rec)

"""**Reasoning**:
Now that Google Drive is mounted, I will load the 'DataCollection.xlsx' file from the specified path into a pandas DataFrame, replacing the previously used dummy data. Then, I will display the first 5 rows, column names and data types, and a concise summary to inspect its structure as requested.


"""

import pandas as pd

df = pd.read_excel('/content/drive/MyDrive/ThesisFiles/DataCollection.xlsx')

print("First 5 rows of the DataFrame:")
print(df.head())

print("\nColumn names and their data types:")
print(df.info())

print("\nConcise summary of the DataFrame:")
print(df.describe(include='all'))

"""## Preprocess Data for Compliance Score Calculation

### Subtask:
Transform the loaded `df` (actual 'DataCollection.xlsx' data) into a format suitable for calculating phase-wise and overall compliance scores. This involves:
1.  **Identifying Organization Name**: Use the 'ID' column as a unique identifier for each organization since a clear 'Organization Name' column is not present. The 'What sector does your organization operate in?' column could provide more descriptive names, but for now, 'ID' will serve for grouping.
2.  **Mapping Questions to Phases**: Based on the common phases of incident management, I will define which questions belong to the 'Before' (Preparation), 'During' (Detection & Analysis, Containment, Eradication & Recovery), and 'After' (Post-Incident Activity) phases. Since a 'ModelPhases.docx' was mentioned but not provided, these mappings will be based on a standard incident response lifecycle and the phrasing of the questions.
3.  **Defining a Scoring Mechanism**: Assign numerical scores to the categorical responses (e.g., 'Yes, and we have the evidence', 'In progress', 'No but planned', 'No', 'Yes, but not sure about the evidence'). A 'Max Score' will also be assigned to each question, typically 10, assuming a full 'Yes, and we have the evidence' answer achieves 100% compliance for that question.
4.  **Reshaping the DataFrame**: Convert the wide-format DataFrame (where each question is a column) into a long format, with columns for 'Organization ID', 'Phase', 'Question Text', 'Answer', 'Score', and 'Max Score'.

### Reasoning:
The current `df` contains raw survey responses in a wide format, with questions as column headers and categorical answers as values. To calculate compliance scores by phase for each organization, the data needs to be restructured. This preprocessing step will create a standardized format that maps responses to numerical scores and associates each question with its relevant incident management phase, enabling the calculation of compliance percentages.

**Reasoning**:
To prepare the data for compliance score calculation, I will first define the question categories for each phase ('Before', 'During', 'After') and a scoring mechanism for the categorical responses. Then, I will reshape the DataFrame, apply the scoring, and introduce 'Organization ID', 'Phase', 'Question Text', 'Score', and 'Max Score' columns.
"""

import numpy as np

phase_questions = {
    'Before': [
        'Does the organization have an information security incident management policy?\n*Evidence required: Incident management policy document.',
        'Does   the organization regularly update the existing information security policies?      \n*Evidence required:\u00a0\u00a0Record of changes to the last policies.      \n  ',
        'Does   the organization have an information security incident management plan?       \n*Evidence required:\u00a0Incident Response Plan.      \n  ',
        'Did the organization establish an Incident Management Team (IMT)?\n*Evidence required:\u00a0IMT structures, hierarchy, roles, and tasks of IMT staff members. ',
        'Did the organization establish an Incident Response Team (IRT)?\n*Evidence required:\u00a0IRT structures, hierarchy, roles, and tasks of IRT staff members.',
        'Did   the organization have an appropriate training plan program for IRT personnel?      \n*Evidence required:\u00a0Training plan and program for IRT personnel. ',
        'Does the organization engage interested parties in incident response management?  \n*Evidence required:\u00a0Document containing communication procedures actions such as: Incident notification procedure...',
        'Does   the organization have an incident management information system according to   IMP?      \n*Evidence required:\u00a0Deployed an incident   management information system.       \n',
        'Does the organization implement controls to prevent and mitigate security   incidents to meet the requirements of the plan?      \n*Evidence required:\u00a0Controls such as: (network security devices, p...',
        'Does   the organization have an awareness and training plan and program on   information security incident and vulnerability management?      \n*Evidence required:\u00a0Information security awareness an...',
        'Does   the organization have a plan to test incident management processes and   procedures?      \n*Evidence required:\u00a0Test plan\n Periodic tests\n Conducting exercises to check   processes/procedure...',
        'Does   the organization execute the existing test plan regularly?      \n*Evidence required:\u00a0Tests results.\n',
        'Does   the organization have an incident response capability monitoring program?\u00a0\n*Evidence required:\u00a0Incident response capability monitoring program.      \n'
    ],
    'During': [
        'Is the organization  monitoring and logging system and network activity?\n*Evidence required:\u00a0Log file\n User Activity Monitoring\n Log Analysis and Alerting\n Network Monitoring.\n',
        'Does   the organization detect and report the occurrence of information security   events or the existence of information security vulnerabilities?      \n*Evidence required:\u00a0Monitoring tools deplo...',
        'Did   the organization have a process in place to collect detailed information and   all news related to this event, and properly log the collected incident data   for later analysis?      \n*Evide...',
        'Did   the organization analyse the external/internal threats to gain an   understanding of the threat environment and the changes that have occurred?      \n*Evidence required:\u00a0Records of incident ...',
        'Did   you communicate information related to the incident occurrence to relevant   stakeholders?      \n*Evidence required:\u00a0Records\u00a0of communication with concerned parties related to the incident o...',
        'Are   IR personnel aware of their responsibilities and have all the necessary   documents needed to perform their duties?       \n*Evidence required:\u00a0Record of documents distribution lists of   res...',
        'Does   the organization evaluate information security events to determine if they   constitute incidents, triage them, and prioritize all information   security\u00a0incidents?      \n*Evidence required...',
        'Does   the organization activate the required response teams?      \n*Evidence required:Records of communication during real   incidents, such as: Emails - Slack/Teams messages - Ticketing system  ...',
        'Does   the organization start the timer for the response?       \n*Evidence required:\u00a0Logs showing automated timer start events/logged   trigger times.      \n',
        'Does   the organization use a documented change management process to ensure proper   control and security of incident related artifacts or documents?      \n*Evidence required:\u00a0Record of approved ...',
        'Does   the organization evaluate the proposed resolution with targeted/affected   teams to confirm it meets their needs?      \n*Evidence required:Formal confirmation that the proposed   resolution...',
        'Does   the IRT properly investigate every reported incident?\u00a0\n*Evidence required:\u00a0Incident   investigation report.      \n',
        'Does   the organization check if the incident is under control; if not, escalate it   to the crisis management team?      \n*Evidence required:\u00a0Completed incident status checklists (containment   v...',
        'Does the organization assign internal resources and identify external resources in   order to respond to an incident?      \n*Evidence required:\u00a0Internal\nExternal Resource Allocation and   identifi...',
        'Does   the organization follow defined communication protocols to notify authorized   internal and external stakeholders about the incident and share necessary   details to support response and re...'
    ],
    'After': [
        'Does   the organization close the incident in accordance with the information   security incident management policy and notify all interested parties?       \n*Evidence required:\u00a0Formal Closure Rec...',
        'Does   the organization review how effective the processes, procedures, reporting,   and organizational structure were in handling and recovering from the incident?      \n*Evidence required:\u00a0Post-...',
        'Does   the organization identify, document, and communicate the lessons learned from   information security incidents?      *Evidence required:\u00a0Lessons Learned Documentation and follow-up tracked ...',
        'Does   the organization review, identify, and improve the implementation and update   of security controls, and update the incident management policy if needed (E2)?      \n*Evidence required:\u00a0Reco...',
        'Does   the organization review, identify, and make improvements to the   organization\'s existing information security risk assessment?      \n*Evidence required:\u00a0Updated risk assessments and regist...',
        'Does   the organization communicate and share the results of review with   trusted/select stakeholders?\u00a0\n*Evidence required:\u00a0Record of shared Communication regarding incidents   after their resolu...',
        'Does   the organization share the results with partners?      \n*Evidence required:\u00a0Record of shared Communication regarding incidents after their resolution with stakeholders and partners.',
        'Does   the organization perform a comprehensive evaluation of IRT performance and   effectiveness periodically?      \n*Evidence required:\u00a0Periodic post-incident team performance reviews: Performan...'
    ]
}

question_to_phase = {}
for phase, questions in phase_questions.items():
    for q in questions:
        question_to_phase[q] = phase

score_mapping = {
    'Yes, and we have the evidence': 10,
    'Yes, but not sure about the evidence': 7,
    'In progress': 5,
    'No but planned': 3,
    'No': 0,
    np.nan: 0
}

MAX_QUESTION_SCORE = 10

df.columns = df.columns.str.strip()

sector_column_name = 'What sector does your organization operate in?'
if sector_column_name not in df.columns:
    print(f"Warning: '{sector_column_name}' not found in DataFrame columns after stripping. Using original name if available.")

question_columns = [col for col in df.columns if col not in ['ID', 'Start time', 'Completion time', 'Email', 'Name', 'Last modified time', 'Do you wish to participate in this study?!', sector_column_name]]

df_long = df.melt(id_vars=['ID', sector_column_name],
                   value_vars=question_columns,
                   var_name='Question Text',
                   value_name='Answer')

df_long['Phase'] = df_long['Question Text'].map(question_to_phase)

df_long['Score'] = df_long['Answer'].map(score_mapping)

df_long['Max Score'] = MAX_QUESTION_SCORE

df_long = df_long.rename(columns={'ID': 'Organization ID'})

org_id_mapping = {4: 'Organization A', 5: 'Organization B', 6: 'Organization C', 7: 'Organization D'}
df_long['Organization ID'] = df_long['Organization ID'].map(org_id_mapping)

df_long.dropna(subset=['Phase'], inplace=True)

print("Preprocessed DataFrame head:")
print(df_long.head())
print("\nPreprocessed DataFrame info:")
print(df_long.info())

"""**Reasoning**:
The data has been successfully preprocessed into a long format (`df_long`) with assigned scores and phases. The next step is to calculate the phase-wise compliance scores for each organization, which involves grouping `df_long` by 'Organization ID' and 'Phase', summing the 'Score' and 'Max Score' for each group, and then computing the compliance percentage.


"""

phase_scores_actual_df = df_long.groupby(['Organization ID', 'Phase']).agg(
    total_score=('Score', 'sum'),
    total_max_score=('Max Score', 'sum')
).reset_index()

phase_scores_actual_df['Compliance Score (%)'] = (phase_scores_actual_df['total_score'] / phase_scores_actual_df['total_max_score']) * 100

print("Phase-wise Compliance Scores (Actual Data):")
print(phase_scores_actual_df[['Organization ID', 'Phase', 'Compliance Score (%)']])

"""**Reasoning**:
The phase-wise compliance scores for the actual data have been calculated. The next step is to calculate the overall compliance score for each organization by grouping the `phase_scores_actual_df` by 'Organization ID' and computing the mean of the 'Compliance Score (%)'.


"""

overall_scores_actual_df = phase_scores_actual_df.groupby('Organization ID')['Compliance Score (%)'].mean().reset_index()

print("Overall Compliance Scores (Actual Data):")
print(overall_scores_actual_df)

"""## Visualize Compliance Scores with a Spider Chart

### Subtask:
Generate a spider chart to visualize the phase-wise compliance scores for each organization. This visualization will help in identifying areas of strength and weakness across the 'Before', 'During', and 'After' phases for each organization.

### Reasoning:
To effectively visualize the multi-dimensional compliance scores (one score for each phase per organization) and facilitate comparison, a spider chart is a suitable choice. This chart type is ideal for displaying performance across several categories or metrics, making it easy to identify which phases each organization performs well in and where they might be lacking.

**Reasoning**:
To prepare the data for the spider chart, I need to pivot the `phase_scores_actual_df` so that 'Phase' values ('Before', 'During', 'After') become columns, with 'Organization ID' as the index and 'Compliance Score (%)' as the values. This format is suitable for plotting multiple organizations on a single spider chart.
"""

import matplotlib.pyplot as plt
import pandas as pd

pivot_df = phase_scores_actual_df.pivot(index='Organization ID', columns='Phase', values='Compliance Score (%)').reset_index()

if not pivot_df.empty:
    expected_phases = ['Before', 'During', 'After']
    existing_phases = [p for p in expected_phases if p in pivot_df.columns]

    if len(existing_phases) == len(expected_phases):
        pivot_df = pivot_df[['Organization ID'] + expected_phases]
    else:
        print(f"Warning: Not all expected phase columns {expected_phases} are present in pivot_df. Existing columns: {pivot_df.columns.tolist()}")
else:
    print("Warning: The pivoted DataFrame (pivot_df) is empty. Cannot generate chart.")

print("Pivoted DataFrame for Chart Visualization:")
print(pivot_df.head())

import matplotlib.pyplot as plt
import numpy as np

# Get the phases (categories) from the pivoted DataFrame
phases = pivot_df.columns[1:].tolist()
num_vars = len(phases)

# Calculate angles for the radar chart axes
angles = np.linspace(0, 2 * np.pi, num_vars, endpoint=False).tolist()
# Complete the loop by adding the first angle to the end
angles += angles[:1]

# Iterate through each organization and create a separate spider chart
for index, row in pivot_df.iterrows():
    org_id_label = row['Organization ID'] # This will now be 'Organization A', 'Organization B', etc.
    values = row[phases].tolist()
    values += values[:1] # Complete the loop for plotting

    fig, ax = plt.subplots(figsize=(6, 6), subplot_kw={'projection': 'polar'})

    # Plot data
    ax.plot(angles, values, linewidth=2, linestyle='solid', label=org_id_label) # Use org_id_label directly
    ax.fill(angles, values, 'b', alpha=0.25)

    # Customize the chart
    ax.set_theta_offset(np.pi / 2)
    ax.set_theta_direction(-1)

    # Draw axis labels and ticks
    plt.xticks(angles[:-1], phases, color='grey', size=12)
    ax.set_rlabel_position(0)
    ax.set_yticks(np.arange(0, 101, 20))
    ax.set_yticklabels([str(x) + '%' for x in np.arange(0, 101, 20)], color='grey', size=10)
    ax.set_ylim(0, 100)

    # Add a title and legend
    ax.set_title(f'Compliance Scores for {org_id_label}', y=1.1, fontsize=14)
    ax.legend(loc='upper right', bbox_to_anchor=(1.3, 1.1))

    plt.show()

import numpy as np

# Define questions for each phase based on their content
# Corrected the list syntax to properly separate string literals
phase_questions = {
    'Before': [
        'Does the organization have an information security incident management policy?\n*Evidence required: Incident management policy document.',
        'Does   the organization regularly update the existing information security policies?      \n*Evidence required:\u00a0\u00a0Record of changes to the last policies.      \n  ',
        'Does   the organization have an information security incident management plan?       \n*Evidence required:\u00a0Incident Response Plan.      \n  ',
        'Did the organization establish an Incident Management Team (IMT)?\n*Evidence required:\u00a0IMT structures, hierarchy, roles, and tasks of IMT staff members. ',
        'Did the organization establish an Incident Response Team (IRT)?\n*Evidence required:\u00a0IRT structures, hierarchy, roles, and tasks of IRT staff members.',
        'Did   the organization have an appropriate training plan program for IRT personnel?      \n*Evidence required:\u00a0Training plan and program for IRT personnel. ',
        'Does the organization engage interested parties in incident response management?  \n*Evidence required:\u00a0Document containing communication procedures actions such as: Incident notification procedure...',
        'Does   the organization have an incident management information system according to   IMP?      \n*Evidence required:\u00a0Deployed an incident   management information system.       \n',
        'Does the organization implement controls to prevent and mitigate security   incidents to meet the requirements of the plan?      \n*Evidence required:\u00a0Controls such as: (network security devices, p...',
        'Does   the organization have an awareness and training plan and program on   information security incident and vulnerability management?      \n*Evidence required:\u00a0Information security awareness an...',
        'Does   the organization have a plan to test incident management processes and   procedures?      \n*Evidence required:\u00a0Test plan\n Periodic tests\n Conducting exercises to check   processes/procedure...',
        'Does   the organization execute the existing test plan regularly?      \n*Evidence required:\u00a0Tests results.\n',
        'Does   the organization have an incident response capability monitoring program?\u00a0\n*Evidence required:\u00a0Incident response capability monitoring program.      \n'
    ],
    'During': [
        'Is the organization  monitoring and logging system and network activity?\n*Evidence required:\u00a0Log file\n User Activity Monitoring\n Log Analysis and Alerting\n Network Monitoring.\n',
        'Does   the organization detect and report the occurrence of information security   events or the existence of information security vulnerabilities?      \n*Evidence required:\u00a0Monitoring tools deplo...',
        'Did   the organization have a process in place to collect detailed information and   all news related to this event, and properly log the collected incident data   for later analysis?      \n*Evide...',
        'Did   the organization analyse the external/internal threats to gain an   understanding of the threat environment and the changes that have occurred?      \n*Evidence required:\u00a0Records of incident ...',
        'Did   you communicate information related to the incident occurrence to relevant   stakeholders?      \n*Evidence required:\u00a0Records\u00a0of communication with concerned parties related to the incident o...',
        'Are   IR personnel aware of their responsibilities and have all the necessary   documents needed to perform their duties?       \n*Evidence required:\u00a0Record of documents distribution lists of   res...',
        'Does   the organization evaluate information security events to determine if they   constitute incidents, triage them, and prioritize all information   security\u00a0incidents?      \n*Evidence required...',
        'Does   the organization activate the required response teams?      \n*Evidence required:Records of communication during real   incidents, such as: Emails - Slack/Teams messages - Ticketing system  ...',
        'Does   the organization start the timer for the response?       \n*Evidence required:\u00a0Logs showing automated timer start events/logged   trigger times.      \n',
        'Does   the organization use a documented change management process to ensure proper   control and security of incident related artifacts or documents?      \n*Evidence required:\u00a0Record of approved ...',
        'Does   the organization evaluate the proposed resolution with targeted/affected   teams to confirm it meets their needs?      \n*Evidence required:Formal confirmation that the proposed   resolution...',
        'Does   the IRT properly investigate every reported incident?\u00a0\n*Evidence required:\u00a0Incident   investigation report.      \n',
        'Does   the organization check if the incident is under control; if not, escalate it   to the crisis management team?      \n*Evidence required:\u00a0Completed incident status checklists (containment   v...',
        'Does the organization assign internal resources and identify external resources in   order to respond to an incident?      \n*Evidence required:\u00a0Internal\nExternal Resource Allocation and   identifi...',
        'Does   the organization follow defined communication protocols to notify authorized   internal and external stakeholders about the incident and share necessary   details to support response and re...'
    ],
    'After': [
        'Does   the organization close the incident in accordance with the information   security incident management policy and notify all interested parties?       \n*Evidence required:\u00a0Formal Closure Rec...',
        'Does   the organization review how effective the processes, procedures, reporting,   and organizational structure were in handling and recovering from the incident?      \n*Evidence required:\u00a0Post-...',
        'Does   the organization identify, document, and communicate the lessons learned from   information security incidents?      *Evidence required:\u00a0Lessons Learned Documentation and follow-up tracked ...',
        'Does   the organization review, identify, and improve the implementation and update   of security controls, and update the incident management policy if needed (E2)?      \n*Evidence required:\u00a0Reco...',
        'Does   the organization review, identify, and make improvements to the   organization\'s existing information security risk assessment?      \n*Evidence required:\u00a0Updated risk assessments and regist...',
        'Does   the organization communicate and share the results of review with   trusted/select stakeholders?\u00a0\n*Evidence required:\u00a0Record of shared Communication regarding incidents   after their resolu...',
        'Does   the organization share the results with partners?      \n*Evidence required:\u00a0Record of shared Communication regarding incidents after their resolution with stakeholders and partners.',
        'Does   the organization perform a comprehensive evaluation of IRT performance and   effectiveness periodically?      \n*Evidence required:\u00a0Periodic post-incident team performance reviews: Performan...'
    ]
}

# Create a reverse mapping for easier lookup
question_to_phase = {}
for phase, questions in phase_questions.items():
    for q in questions:
        question_to_phase[q] = phase

# Define the scoring mechanism
score_mapping = {
    'Yes, and we have the evidence': 10,
    'Yes, but not sure about the evidence': 7,
    'In progress': 5,
    'No but planned': 3,
    'No': 0,
    np.nan: 0 # Treat NaN as 'No' or non-applicable, thus 0 score
}

# Max score for each question
MAX_QUESTION_SCORE = 10

# Clean column names by stripping whitespace (already done in previous execution, ensuring consistency)
df.columns = df.columns.str.strip()

# Identify question columns to melt. Use the cleaned column name for 'What sector...' if it exists.
sector_column_name = 'What sector does your organization operate in?'
# Ensure this column name is present after stripping
if sector_column_name not in df.columns:
    print(f"Warning: '{sector_column_name}' not found in DataFrame columns after stripping. Using original name if available.")
    # This part should ideally not be hit if stripping works as expected on the original name.

question_columns = [col for col in df.columns if col not in ['ID', 'Start time', 'Completion time', 'Email', 'Name', 'Last modified time', 'Do you wish to participate in this study?!', sector_column_name]]

# Melt the DataFrame to long format
df_long = df.melt(id_vars=['ID', sector_column_name],
                   value_vars=question_columns,
                   var_name='Question Text',
                   value_name='Answer')

# Map the 'Question Text' to 'Phase'
df_long['Phase'] = df_long['Question Text'].map(question_to_phase)

# Map the 'Answer' to 'Score'
df_long['Score'] = df_long['Answer'].map(score_mapping)

# Add 'Max Score' column
df_long['Max Score'] = MAX_QUESTION_SCORE

# Rename 'ID' to 'Organization ID' for clarity
df_long = df_long.rename(columns={'ID': 'Organization ID'})

# Map numerical Organization IDs to alphabetical names
org_id_mapping = {4: 'Organization A', 5: 'Organization B', 6: 'Organization C', 7: 'Organization D'}
df_long['Organization ID'] = df_long['Organization ID'].map(org_id_mapping)

# Drop rows where 'Phase' is NaN (questions not mapped, if any)
df_long.dropna(subset=['Phase'], inplace=True)

# Display the first few rows of the preprocessed DataFrame and its info
print("Preprocessed DataFrame head:")
print(df_long.head())
print("\nPreprocessed DataFrame info:")
print(df_long.info())

phase_scores_actual_df = df_long.groupby(['Organization ID', 'Phase']).agg(
    total_score=('Score', 'sum'),
    total_max_score=('Max Score', 'sum')
).reset_index()

phase_scores_actual_df['Compliance Score (%)'] = (phase_scores_actual_df['total_score'] / phase_scores_actual_df['total_max_score']) * 100

# Display the resulting DataFrame
print("Phase-wise Compliance Scores (Actual Data):")
print(phase_scores_actual_df[['Organization ID', 'Phase', 'Compliance Score (%)']])

import matplotlib.pyplot as plt
import pandas as pd

# Pivot the phase_scores_actual_df to get phases as columns for spider chart
pivot_df = phase_scores_actual_df.pivot(index='Organization ID', columns='Phase', values='Compliance Score (%)').reset_index()

# Check if pivot_df is empty before reordering columns
if not pivot_df.empty:
    # Reorder columns to ensure consistent order for phases: Before, During, After
    # Ensure all expected phase columns exist before attempting to reorder
    expected_phases = ['Before', 'During', 'After']
    existing_phases = [p for p in expected_phases if p in pivot_df.columns]

    if len(existing_phases) == len(expected_phases):
        pivot_df = pivot_df[['Organization ID'] + expected_phases]
    else:
        print(f"Warning: Not all expected phase columns {expected_phases} are present in pivot_df. Existing columns: {pivot_df.columns.tolist()}")
else:
    print("Warning: The pivoted DataFrame (pivot_df) is empty. Cannot generate spider chart.")

print("Pivoted DataFrame for Spider Chart:")
print(pivot_df.head())

"""**Reasoning**:
Now that the data is pivoted into the correct format, I will create a spider chart to visualize the phase-wise compliance scores for each organization. This involves setting up the polar plot, defining the angles for each phase, and plotting the scores for every organization.


"""

import matplotlib.pyplot as plt
import numpy as np

phases = ['Before', 'During', 'After']
org_ids = pivot_df['Organization ID'].tolist()

fig, axes = plt.subplots(1, 3, figsize=(18, 6), sharey=True)
fig.suptitle('Phase-wise Compliance Scores Across Organizations', fontsize=16)

for i, phase in enumerate(phases):
    ax = axes[i]
    scores = pivot_df[phase].tolist()

    ax.bar(org_ids, scores, color='skyblue')

    ax.set_title(f'Compliance Score for {phase} Phase')
    ax.set_xlabel('Organization Name')
    ax.set_ylabel('Compliance Score (%)')
    ax.set_ylim(0, 100)
    ax.tick_params(axis='x', rotation=45)

    for bar in ax.patches:
        ax.text(bar.get_x() + bar.get_width() / 2,
                bar.get_height() + 2,
                f'{bar.get_height():.1f}%',
                ha='center', va='bottom')

plt.tight_layout(rect=[0, 0.03, 1, 0.95])
plt.show()

"""**Reasoning**:
Now that the data is pivoted into the correct format, I will create a spider chart to visualize the phase-wise compliance scores for each organization. This involves setting up the polar plot, defining the angles for each phase, and plotting the scores for every organization.

"""

import matplotlib.pyplot as plt
import numpy as np

# Get the phases (categories) from the pivoted DataFrame
phases = pivot_df.columns[1:].tolist()
num_vars = len(phases)

# Calculate angles for the radar chart axes
angles = np.linspace(0, 2 * np.pi, num_vars, endpoint=False).tolist()
# Complete the loop by adding the first angle to the end
angles += angles[:1]

# Iterate through each organization and create a separate spider chart
for index, row in pivot_df.iterrows():
    org_id_label = row['Organization ID'] # This will now be 'Organization A', 'Organization B', etc.
    values = row[phases].tolist()
    values += values[:1] # Complete the loop for plotting

    fig, ax = plt.subplots(figsize=(6, 6), subplot_kw={'projection': 'polar'})

    # Plot data
    ax.plot(angles, values, linewidth=2, linestyle='solid', label=org_id_label) # Use org_id_label directly
    ax.fill(angles, values, 'b', alpha=0.25)

    # Customize the chart
    ax.set_theta_offset(np.pi / 2)
    ax.set_theta_direction(-1)

    # Draw axis labels and ticks
    plt.xticks(angles[:-1], phases, color='grey', size=12)
    ax.set_rlabel_position(0)
    ax.set_yticks(np.arange(0, 101, 20))
    ax.set_yticklabels([str(x) + '%' for x in np.arange(0, 101, 20)], color='grey', size=10)
    ax.set_ylim(0, 100)

    # Add a title and legend
    ax.set_title(f'Compliance Scores for {org_id_label}', y=1.1, fontsize=14)
    ax.legend(loc='upper right', bbox_to_anchor=(1.3, 1.1))

    plt.show()

"""## Summary:

### Q&A
The analysis successfully calculated compliance scores, visualized them, and identified weaknesses.
*   **Compliance Scores**: Phase-wise and overall compliance scores were calculated for each organization. For example, Organization 4 showed phase scores of Before: 100.00%, During: 100.00%, After: 87.50%, with an overall average of 95.83%. Organization 5 had scores of Before: 56.00%, During: 73.64%, After: 40.00%, averaging 56.55%.
*   **Spider Charts**: Individual spider charts were generated for each organization to visualize their phase-wise compliance scores across the 'Before', 'During', and 'After' phases, allowing for a detailed view of each organization's performance.
*   **Identified Weaknesses and Recommendations**:
    *   **Organization 4**: Weakness in the 'After' phase (Score: 87.50%). Recommendation: Enhance post-incident activities such as formal incident closure, thorough post-incident reviews to assess effectiveness, comprehensive identification and communication of lessons learned, and implementing improvements to security controls and risk assessments based on these lessons. Ensure results are shared with relevant stakeholders and partners.
    *   **Organization 5**: Weakness in the 'After' phase (Score: 40.00%). Recommendation: Enhance post-incident activities such as formal incident closure, thorough post-incident reviews to assess effectiveness, comprehensive identification and communication of lessons learned, and implementing improvements to security controls and risk assessments based on these lessons. Ensure results are shared with relevant stakeholders and partners.
    *   **Organization 6**: Weakness in the 'During' phase (Score: 41.82%). Recommendation: Improve incident detection, analysis, and response capabilities. This includes enhancing monitoring and logging, improving event detection and reporting, streamlining incident investigation and containment procedures, and ensuring timely communication with stakeholders during an active incident.
    *   **Organization 7**: Weakness in the 'After' phase (Score: 53.75%). Recommendation: Enhance post-incident activities such as formal incident closure, thorough post-incident reviews to assess effectiveness, comprehensive identification and communication of lessons learned, and implementing improvements to security controls and risk assessments based on these lessons. Ensure results are shared with relevant stakeholders and partners.

### Data Analysis Key Findings
*   **Data Preprocessing was Crucial**: The raw survey data required significant preprocessing, including cleaning column names, mapping questions to specific incident management phases ('Before', 'During', 'After'), and assigning numerical scores to categorical responses. This step was critical to transform the data into a usable format for compliance calculation.
*   **Diverse Compliance Performance Across Organizations**: There is a noticeable variation in compliance scores across different organizations and phases. For instance, Organization 4 shows strong performance in 'Before' and 'During' phases, while Organization 5 struggles most in the 'After' phase.
*   **Varying Weakness Across Phases**: The analysis revealed that weaknesses are not concentrated in a single phase across all organizations. For example, Organization 6's primary weakness is in the 'During' phase, while Organizations 4, 5, and 7 show their lowest scores in the 'After' phase.
*   **Overall Compliance Varies**: Overall compliance scores ranged from 46.94% (Organization 6) to 95.83% (Organization 4), indicating a spectrum of adherence to incident management best practices among the surveyed organizations.

### Insights or Next Steps
*   **Targeted Improvement Programs**: Organizations should leverage the identified weakest phases and corresponding recommendations to develop targeted improvement programs, focusing on specific policies, training, or technical controls relevant to their lowest-scoring areas.
*   **Phase-Specific Focus**: The results highlight the importance of addressing specific phases. Organizations performing well in one phase but poorly in another should prioritize improvements in their weaker areas rather than adopting a one-size-generates-all approach.

## Identify Weaknesses and Provide Recommendations

### Subtask:
Analyze the generated spider chart to identify areas of weakness (phases with lower compliance scores) for each organization. Based on these weaknesses, provide general recommendations for improvement.

### Reasoning:
By visually inspecting the spider chart, we can quickly spot which phases have lower scores for each organization. This allows for targeted recommendations that address specific areas where compliance needs improvement. For example, if an organization has a low 'Before' phase score, recommendations would focus on preparedness, policy, and planning.

## Summary:

### Q&A
The analysis successfully calculated compliance scores, visualized them, and identified weaknesses.
*   **Compliance Scores**: Phase-wise and overall compliance scores were calculated for each organization. For example, Organization 1 showed phase scores of Before: 76.92%, During: 50.00%, After: 50.00%, with an overall average of 58.97%. Organization 2 had scores of Before: 69.23%, During: 53.33%, After: 75.00%, averaging 65.85%.
*   **Spider Chart**: A spider chart was generated to visualize the phase-wise compliance scores for each organization, allowing for a comparative view of performance across the 'Before', 'During', and 'After' phases.
*   **Identified Weaknesses and Recommendations**:
    *   **Organization 1**: Weakness in the 'During' and 'After' phases (both 50.00%). Recommendation: Improve incident detection, analysis, response, post-incident closure, review, and lessons learned.
    *   **Organization 2**: Weakness in the 'During' phase (53.33%). Recommendation: Enhance monitoring, logging, event detection, incident investigation, containment, and communication during active incidents.
    *   **Organization 3**: Weakness in the 'During' phase (46.67%). Recommendation: Improve incident detection, analysis, response, monitoring, logging, event detection, incident investigation, containment, and communication during active incidents.
    *   **Organization 4**: Weakness in the 'During' phase (33.33%). Recommendation: Improve incident detection, analysis, response, monitoring, logging, event detection, incident investigation, containment, and communication during active incidents.
    *   **Organization 5**: Weakness in the 'During' phase (30.00%). Recommendation: Improve incident detection, analysis, response, monitoring, logging, event detection, incident investigation, containment, and communication during active incidents.
    *   **Organization 6**: Weakness in the 'Before' phase (53.85%). Recommendation: Strengthen incident preparedness, including policy, planning, team establishment, training, and regular testing.

### Data Analysis Key Findings
*   **Data Preprocessing was Crucial**: The raw survey data required significant preprocessing, including cleaning column names, mapping questions to specific incident management phases ('Before', 'During', 'After'), and assigning numerical scores to categorical responses. This step was critical to transform the data into a usable format for compliance calculation.
*   **Diverse Compliance Performance Across Organizations**: There is a noticeable variation in compliance scores across different organizations and phases. For instance, Organization 1 has its lowest scores in 'During' and 'After' phases (50.00% for both), while Organization 6 struggles most in the 'Before' phase (53.85%).
*   **"During" Phase as a Common Weakness**: A significant number of organizations (Organizations 2, 3, 4, 5) showed their lowest compliance scores in the 'During' phase, with scores ranging from 30.00% to 53.33%. This suggests a common area for improvement in incident detection, analysis, and response capabilities.
*   **Overall Compliance Varies**: Overall compliance scores ranged from 46.41% (Organization 4) to 65.85% (Organization 2), indicating a spectrum of adherence to incident management best practices among the surveyed organizations.

### Insights or Next Steps
*   **Targeted Improvement Programs**: Organizations should leverage the identified weakest phases and corresponding recommendations to develop targeted improvement programs, focusing on specific policies, training, or technical controls relevant to their lowest-scoring areas.
*   **Deep Dive into "During" Phase Challenges**: Given that the "During" phase is a common weakness, a deeper investigation could be conducted to understand the specific hurdles organizations face in real-time incident detection, analysis, and response, potentially through follow-up interviews or process audits.

# Stage 6: Rcommendations

6.1. API setup cell
"""

from google.colab import userdata
import os

os.environ["OPENAI_API_KEY"] = userdata.get("OPENAI_API_KEY")

!pip -q install openai

# from openai import OpenAI

# client = OpenAI()

# response = client.responses.create(
#     model="gpt-4.1-mini",
#     input="Say hello in one short sentence."
# )

# print(response.output_text)

import re
import json
import pandas as pd

# -----------------------------
# 1) Choose what "weakness" means
# -----------------------------
# Your scoring is 0–10. Common choice:
# - 10 = perfect (strong)
# - 7  = okay
# - 5  = weak
WEAKNESS_SCORE_CUTOFF = 7     # <= 7 will be treated as a weakness (edit if you want)
TOP_N_WEAKNESSES = 8          # send only the worst 8 to the model (keeps output clean & cheaper)

# -----------------------------
# 2) Helper: split evidence from Question Text (because your questions contain "*Evidence required:")
# -----------------------------
def split_question_and_evidence(qtext: str):
    if not isinstance(qtext, str):
        return ("", "")
    parts = re.split(r"\*Evidence required:\s*", qtext, maxsplit=1)
    question = parts[0].strip()
    evidence = parts[1].strip() if len(parts) > 1 else ""
    return question, evidence

# -----------------------------
# 3) Build weaknesses list from the ACTUAL Excel data (df_long)
# -----------------------------
weak_df = df_long[df_long["Score"] <= WEAKNESS_SCORE_CUTOFF].copy()

# If there are no weaknesses, stop early
if weak_df.empty:
    print("No weaknesses found with this cutoff. Try increasing WEAKNESS_SCORE_CUTOFF.")
else:
    # Sort weakest first (lowest score)
    weak_df = weak_df.sort_values(["Organization ID", "Score"], ascending=[True, True])

    # Keep only TOP N per organization
    weak_df = weak_df.groupby("Organization ID").head(TOP_N_WEAKNESSES).reset_index(drop=True)

    # Create a structured list for each organization
    org_to_weaknesses = {}

    for org, group in weak_df.groupby("Organization ID"):
        items = []
        for _, row in group.iterrows():
            q, ev = split_question_and_evidence(row["Question Text"])
            items.append({
                "phase": str(row["Phase"]),
                "question_or_criterion": q,
                "score_out_of_10": float(row["Score"]),
                "suggested_evidence": ev
            })
        org_to_weaknesses[org] = items

    print("Organizations found:", list(org_to_weaknesses.keys()))
    print("Example weaknesses for first org:")
    first_org = list(org_to_weaknesses.keys())[0]
    print(json.dumps(org_to_weaknesses[first_org], indent=2, ensure_ascii=False))

# -----------------------------
# 4) Prompt builder (uses weaknesses from Excel)
# -----------------------------
def build_prompt(org_name, weaknesses):
    return f"""
You are an ISO/IEC 27035 incident management coach.

Organization: {org_name}

The following are weaknesses found from the assessment data (real scores 0–10):
{json.dumps(weaknesses, indent=2, ensure_ascii=False)}

Task:
For EACH weakness:
1) Explain briefly (1–2 lines) why it matters.
2) Give 3–6 practical improvement steps aligned with ISO/IEC 27035.
3) Suggest evidence the organization should prepare (documents/records/logs).
4) Assign a priority (High / Medium / Low).

Write in simple, clear language suitable for corporate setup.
"""

# -----------------------------
# 5) Call the model for each organization + save results
# -----------------------------
from openai import OpenAI
client = OpenAI()

rows = []
for org_name, weaknesses in org_to_weaknesses.items():
    resp = client.responses.create(
        model="gpt-4.1-mini",
        input=build_prompt(org_name, weaknesses)
    )
    rec_text = resp.output_text

    rows.append({
        "Organization": org_name,
        "Weaknesses_Sent": json.dumps(weaknesses, ensure_ascii=False),
        "Recommendations": rec_text
    })

df_recommendations = pd.DataFrame(rows)
display(df_recommendations)

# Export to Excel (new output file)
output_file = "Weaknesses_and_Recommendations.xlsx"
df_recommendations.to_excel(output_file, index=False)
print("Saved:", output_file)

"""# 6.3. Customized Recs"""

!pip -q install gradio

import gradio as gr
import pandas as pd
import json
import re
from openai import OpenAI

client = OpenAI()

# ---------- Helpers ----------
def split_question_and_evidence(qtext: str):
    if not isinstance(qtext, str):
        return ("", "")
    parts = re.split(r"\*Evidence required:\s*", qtext, maxsplit=1)
    question = parts[0].strip()
    evidence = parts[1].strip() if len(parts) > 1 else ""
    return question, evidence

def build_weaknesses_from_df_long(org_id, cutoff=7, top_n=8):
    # Filter just this org
    df_org = df_long[df_long["Organization ID"] == org_id].copy()
    if df_org.empty:
        return []

    # Weakness rule
    weak = df_org[df_org["Score"] <= cutoff].copy()
    weak = weak.sort_values("Score", ascending=True).head(top_n)

    weaknesses = []
    for _, row in weak.iterrows():
        q, ev = split_question_and_evidence(row["Question Text"])
        weaknesses.append({
            "phase": str(row["Phase"]),
            "question_or_criterion": q,
            "score_out_of_10": float(row["Score"]),
            "suggested_evidence": ev
        })
    return weaknesses

def build_prompt(org_name, weaknesses):
    return f"""
You are an ISO/IEC 27035 incident management coach.

Organization: {org_name}

Weaknesses found from assessment data (real scores 0–10):
{json.dumps(weaknesses, indent=2, ensure_ascii=False)}

Task:
For EACH weakness:
1) Explain briefly (1–2 lines) why it matters.
2) Give 3–6 practical improvement steps aligned with ISO/IEC 27035.
3) Suggest evidence the organization should prepare (documents/records/logs).
4) Assign a priority (High / Medium / Low).

Write in simple, clear language suitable for corporate setup.
"""

def get_recommendations_for_org(org_id, cutoff, top_n, model_name):
    weaknesses = build_weaknesses_from_df_long(org_id, cutoff=int(cutoff), top_n=int(top_n))

    if not weaknesses:
        return (
            "No weaknesses found for this organization using the selected cutoff.\n"
            "Try increasing the cutoff (e.g., 8 or 9).",
            "[]"
        )

    resp = client.responses.create(
        model=model_name,
        input=build_prompt(org_id, weaknesses)
    )

    # Return: recommendations + the exact weaknesses used
    return resp.output_text, json.dumps(weaknesses, indent=2, ensure_ascii=False)

# ---------- UI Options ----------
org_list = sorted(df_long["Organization ID"].dropna().unique().tolist())

demo = gr.Interface(
    fn=get_recommendations_for_org,
    inputs=[
        gr.Dropdown(choices=org_list, label="Choose Organization"),
        gr.Slider(minimum=0, maximum=10, value=7, step=1, label="Weakness cutoff (<= this score is weak)"),
        gr.Slider(minimum=1, maximum=20, value=8, step=1, label="How many weaknesses to send (Top N)"),
        gr.Dropdown(choices=["gpt-4.1-mini", "gpt-4o-mini"], value="gpt-4.1-mini", label="Model"),
    ],
    outputs=[
        gr.Textbox(label="Recommendations (ISO/IEC 27035-aligned)", lines=18),
        gr.Textbox(label="Weaknesses used in the prompt (from your Excel data)", lines=12),
    ],
    title="Incident Management Improvement Recommendations",
    description="Select an organization, choose a weakness cutoff, then generate evidence-based recommendations."
)

demo.launch(share=True)

